name: CI - Lambda2 Tests

on:
  push:
    branches: [ "lambda2" ]
  pull_request:
    branches: [ "lambda2" ]
  workflow_dispatch:

jobs:
  test-lambda2:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Verify branch
        run: |
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          if [[ "$CURRENT_BRANCH" != "lambda2" ]]; then
            echo "This workflow only runs on lambda1 branch."
            exit 1
          fi

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests for Lambda2
        run: pytest test_lambda2.py
